/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const CategoryId = IDL.Nat;
export const Category = IDL.Record({
  'id' : CategoryId,
  'name' : IDL.Text,
  'description' : IDL.Text,
  'imageUrl' : IDL.Text,
  'videoUrl' : IDL.Opt(IDL.Text),
});
export const ProductId = IDL.Nat;
export const Product = IDL.Record({
  'id' : ProductId,
  'categoryId' : CategoryId,
  'imageUrls' : IDL.Vec(IDL.Text),
  'name' : IDL.Text,
  'description' : IDL.Text,
  'discountPercent' : IDL.Nat,
  'discountEnabled' : IDL.Bool,
  'available' : IDL.Bool,
  'slotIndex' : IDL.Nat,
  'price' : IDL.Nat,
  'videoUrl' : IDL.Opt(IDL.Text),
});
export const Review = IDL.Record({
  'id' : IDL.Nat,
  'createdAt' : IDL.Int,
  'productId' : IDL.Nat,
  'reviewerName' : IDL.Text,
  'comment' : IDL.Text,
  'rating' : IDL.Nat,
});
export const Announcement = IDL.Record({
  'id' : IDL.Text,
  'createdAt' : IDL.Int,
  'isActive' : IDL.Bool,
  'message' : IDL.Text,
});
export const OrderId = IDL.Nat;
export const OrderItem = IDL.Record({
  'productId' : ProductId,
  'productName' : IDL.Text,
  'quantity' : IDL.Nat,
  'price' : IDL.Nat,
});
export const Order = IDL.Record({
  'id' : OrderId,
  'customerName' : IDL.Text,
  'status' : IDL.Text,
  'paymentMethod' : IDL.Text,
  'city' : IDL.Text,
  'createdAt' : IDL.Int,
  'totalAmount' : IDL.Nat,
  'address' : IDL.Text,
  'phone' : IDL.Text,
  'items' : IDL.Vec(OrderItem),
});
export const PlaceOrderRequest = IDL.Record({
  'customerName' : IDL.Text,
  'paymentMethod' : IDL.Text,
  'city' : IDL.Text,
  'address' : IDL.Text,
  'phone' : IDL.Text,
  'items' : IDL.Vec(OrderItem),
});

export const idlService = IDL.Service({
  'addCategory' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Opt(IDL.Text)],
      [Category],
      [],
    ),
  'addProduct' : IDL.Func(
      [
        CategoryId,
        IDL.Text,
        IDL.Text,
        IDL.Nat,
        IDL.Vec(IDL.Text),
        IDL.Opt(IDL.Text),
        IDL.Bool,
        IDL.Nat,
        IDL.Bool,
        IDL.Nat,
      ],
      [Product],
      [],
    ),
  'addReview' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Nat, IDL.Text],
      [IDL.Variant({ 'ok' : Review, 'err' : IDL.Text })],
      [],
    ),
  'adminLogin' : IDL.Func([IDL.Text], [IDL.Bool], []),
  'deleteCategory' : IDL.Func([CategoryId], [IDL.Bool], []),
  'deleteProduct' : IDL.Func([ProductId], [IDL.Bool], []),
  'getActiveAnnouncement' : IDL.Func([], [IDL.Opt(Announcement)], ['query']),
  'getAllOrders' : IDL.Func([], [IDL.Vec(Order)], ['query']),
  'getAllProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
  'getCategories' : IDL.Func([], [IDL.Vec(Category)], ['query']),
  'getProductReviews' : IDL.Func([IDL.Nat], [IDL.Vec(Review)], ['query']),
  'getProductSlots' : IDL.Func([CategoryId], [IDL.Vec(Product)], ['query']),
  'getProductsByCategory' : IDL.Func(
      [CategoryId],
      [IDL.Vec(Product)],
      ['query'],
    ),
  'initializeCategorySlots' : IDL.Func([CategoryId], [IDL.Bool], []),
  'placeOrder' : IDL.Func([PlaceOrderRequest], [Order], []),
  'setAdminPassword' : IDL.Func([IDL.Text, IDL.Text], [IDL.Bool], []),
  'setAnnouncement' : IDL.Func([IDL.Text, IDL.Bool], [IDL.Bool], []),
  'toggleAnnouncement' : IDL.Func([IDL.Bool], [IDL.Bool], []),
  'updateCategory' : IDL.Func(
      [CategoryId, IDL.Text, IDL.Text, IDL.Text, IDL.Opt(IDL.Text)],
      [IDL.Bool],
      [],
    ),
  'updateOrderStatus' : IDL.Func([OrderId, IDL.Text], [IDL.Bool], []),
  'updateProduct' : IDL.Func(
      [
        ProductId,
        CategoryId,
        IDL.Text,
        IDL.Text,
        IDL.Nat,
        IDL.Vec(IDL.Text),
        IDL.Opt(IDL.Text),
        IDL.Bool,
        IDL.Nat,
        IDL.Bool,
        IDL.Nat,
      ],
      [IDL.Bool],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const CategoryId = IDL.Nat;
  const Category = IDL.Record({
    'id' : CategoryId,
    'name' : IDL.Text,
    'description' : IDL.Text,
    'imageUrl' : IDL.Text,
    'videoUrl' : IDL.Opt(IDL.Text),
  });
  const ProductId = IDL.Nat;
  const Product = IDL.Record({
    'id' : ProductId,
    'categoryId' : CategoryId,
    'imageUrls' : IDL.Vec(IDL.Text),
    'name' : IDL.Text,
    'description' : IDL.Text,
    'discountPercent' : IDL.Nat,
    'discountEnabled' : IDL.Bool,
    'available' : IDL.Bool,
    'slotIndex' : IDL.Nat,
    'price' : IDL.Nat,
    'videoUrl' : IDL.Opt(IDL.Text),
  });
  const Review = IDL.Record({
    'id' : IDL.Nat,
    'createdAt' : IDL.Int,
    'productId' : IDL.Nat,
    'reviewerName' : IDL.Text,
    'comment' : IDL.Text,
    'rating' : IDL.Nat,
  });
  const Announcement = IDL.Record({
    'id' : IDL.Text,
    'createdAt' : IDL.Int,
    'isActive' : IDL.Bool,
    'message' : IDL.Text,
  });
  const OrderId = IDL.Nat;
  const OrderItem = IDL.Record({
    'productId' : ProductId,
    'productName' : IDL.Text,
    'quantity' : IDL.Nat,
    'price' : IDL.Nat,
  });
  const Order = IDL.Record({
    'id' : OrderId,
    'customerName' : IDL.Text,
    'status' : IDL.Text,
    'paymentMethod' : IDL.Text,
    'city' : IDL.Text,
    'createdAt' : IDL.Int,
    'totalAmount' : IDL.Nat,
    'address' : IDL.Text,
    'phone' : IDL.Text,
    'items' : IDL.Vec(OrderItem),
  });
  const PlaceOrderRequest = IDL.Record({
    'customerName' : IDL.Text,
    'paymentMethod' : IDL.Text,
    'city' : IDL.Text,
    'address' : IDL.Text,
    'phone' : IDL.Text,
    'items' : IDL.Vec(OrderItem),
  });
  
  return IDL.Service({
    'addCategory' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Opt(IDL.Text)],
        [Category],
        [],
      ),
    'addProduct' : IDL.Func(
        [
          CategoryId,
          IDL.Text,
          IDL.Text,
          IDL.Nat,
          IDL.Vec(IDL.Text),
          IDL.Opt(IDL.Text),
          IDL.Bool,
          IDL.Nat,
          IDL.Bool,
          IDL.Nat,
        ],
        [Product],
        [],
      ),
    'addReview' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Nat, IDL.Text],
        [IDL.Variant({ 'ok' : Review, 'err' : IDL.Text })],
        [],
      ),
    'adminLogin' : IDL.Func([IDL.Text], [IDL.Bool], []),
    'deleteCategory' : IDL.Func([CategoryId], [IDL.Bool], []),
    'deleteProduct' : IDL.Func([ProductId], [IDL.Bool], []),
    'getActiveAnnouncement' : IDL.Func([], [IDL.Opt(Announcement)], ['query']),
    'getAllOrders' : IDL.Func([], [IDL.Vec(Order)], ['query']),
    'getAllProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
    'getCategories' : IDL.Func([], [IDL.Vec(Category)], ['query']),
    'getProductReviews' : IDL.Func([IDL.Nat], [IDL.Vec(Review)], ['query']),
    'getProductSlots' : IDL.Func([CategoryId], [IDL.Vec(Product)], ['query']),
    'getProductsByCategory' : IDL.Func(
        [CategoryId],
        [IDL.Vec(Product)],
        ['query'],
      ),
    'initializeCategorySlots' : IDL.Func([CategoryId], [IDL.Bool], []),
    'placeOrder' : IDL.Func([PlaceOrderRequest], [Order], []),
    'setAdminPassword' : IDL.Func([IDL.Text, IDL.Text], [IDL.Bool], []),
    'setAnnouncement' : IDL.Func([IDL.Text, IDL.Bool], [IDL.Bool], []),
    'toggleAnnouncement' : IDL.Func([IDL.Bool], [IDL.Bool], []),
    'updateCategory' : IDL.Func(
        [CategoryId, IDL.Text, IDL.Text, IDL.Text, IDL.Opt(IDL.Text)],
        [IDL.Bool],
        [],
      ),
    'updateOrderStatus' : IDL.Func([OrderId, IDL.Text], [IDL.Bool], []),
    'updateProduct' : IDL.Func(
        [
          ProductId,
          CategoryId,
          IDL.Text,
          IDL.Text,
          IDL.Nat,
          IDL.Vec(IDL.Text),
          IDL.Opt(IDL.Text),
          IDL.Bool,
          IDL.Nat,
          IDL.Bool,
          IDL.Nat,
        ],
        [IDL.Bool],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };