/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Announcement {
  'id' : string,
  'createdAt' : bigint,
  'isActive' : boolean,
  'message' : string,
}
export interface Category {
  'id' : CategoryId,
  'name' : string,
  'description' : string,
  'imageUrl' : string,
  'videoUrl' : [] | [string],
}
export type CategoryId = bigint;
export interface Order {
  'id' : OrderId,
  'customerName' : string,
  'status' : string,
  'paymentMethod' : string,
  'city' : string,
  'createdAt' : bigint,
  'totalAmount' : bigint,
  'address' : string,
  'phone' : string,
  'items' : Array<OrderItem>,
}
export type OrderId = bigint;
export interface OrderItem {
  'productId' : ProductId,
  'productName' : string,
  'quantity' : bigint,
  'price' : bigint,
}
export interface PlaceOrderRequest {
  'customerName' : string,
  'paymentMethod' : string,
  'city' : string,
  'address' : string,
  'phone' : string,
  'items' : Array<OrderItem>,
}
export interface Product {
  'id' : ProductId,
  'categoryId' : CategoryId,
  'imageUrls' : Array<string>,
  'name' : string,
  'description' : string,
  'discountPercent' : bigint,
  'discountEnabled' : boolean,
  'available' : boolean,
  'slotIndex' : bigint,
  'price' : bigint,
  'videoUrl' : [] | [string],
}
export type ProductId = bigint;
export interface Review {
  'id' : bigint,
  'createdAt' : bigint,
  'productId' : bigint,
  'reviewerName' : string,
  'comment' : string,
  'rating' : bigint,
}
export interface _SERVICE {
  'addCategory' : ActorMethod<
    [string, string, string, [] | [string]],
    Category
  >,
  'addProduct' : ActorMethod<
    [
      CategoryId,
      string,
      string,
      bigint,
      Array<string>,
      [] | [string],
      boolean,
      bigint,
      boolean,
      bigint,
    ],
    Product
  >,
  'addReview' : ActorMethod<
    [bigint, string, bigint, string],
    { 'ok' : Review } |
      { 'err' : string }
  >,
  'adminLogin' : ActorMethod<[string], boolean>,
  'deleteCategory' : ActorMethod<[CategoryId], boolean>,
  'deleteProduct' : ActorMethod<[ProductId], boolean>,
  'getActiveAnnouncement' : ActorMethod<[], [] | [Announcement]>,
  'getAllOrders' : ActorMethod<[], Array<Order>>,
  'getAllProducts' : ActorMethod<[], Array<Product>>,
  'getCategories' : ActorMethod<[], Array<Category>>,
  'getProductReviews' : ActorMethod<[bigint], Array<Review>>,
  'getProductSlots' : ActorMethod<[CategoryId], Array<Product>>,
  'getProductsByCategory' : ActorMethod<[CategoryId], Array<Product>>,
  'initializeCategorySlots' : ActorMethod<[CategoryId], boolean>,
  'placeOrder' : ActorMethod<[PlaceOrderRequest], Order>,
  'setAdminPassword' : ActorMethod<[string, string], boolean>,
  'setAnnouncement' : ActorMethod<[string, boolean], boolean>,
  'toggleAnnouncement' : ActorMethod<[boolean], boolean>,
  'updateCategory' : ActorMethod<
    [CategoryId, string, string, string, [] | [string]],
    boolean
  >,
  'updateOrderStatus' : ActorMethod<[OrderId, string], boolean>,
  'updateProduct' : ActorMethod<
    [
      ProductId,
      CategoryId,
      string,
      string,
      bigint,
      Array<string>,
      [] | [string],
      boolean,
      bigint,
      boolean,
      bigint,
    ],
    boolean
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];