/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface PlaceOrderRequest {
    customerName: string;
    paymentMethod: string;
    city: string;
    address: string;
    phone: string;
    items: Array<OrderItem>;
}
export interface Review {
    id: bigint;
    createdAt: bigint;
    productId: bigint;
    reviewerName: string;
    comment: string;
    rating: bigint;
}
export interface Category {
    id: CategoryId;
    name: string;
    description: string;
    imageUrl: string;
    videoUrl?: string;
}
export interface OrderItem {
    productId: ProductId;
    productName: string;
    quantity: bigint;
    price: bigint;
}
export type CategoryId = bigint;
export interface Announcement {
    id: string;
    createdAt: bigint;
    isActive: boolean;
    message: string;
}
export type ProductId = bigint;
export interface Order {
    id: OrderId;
    customerName: string;
    status: string;
    paymentMethod: string;
    city: string;
    createdAt: bigint;
    totalAmount: bigint;
    address: string;
    phone: string;
    items: Array<OrderItem>;
}
export type OrderId = bigint;
export interface Product {
    id: ProductId;
    categoryId: CategoryId;
    imageUrls: Array<string>;
    name: string;
    description: string;
    discountPercent: bigint;
    discountEnabled: boolean;
    available: boolean;
    slotIndex: bigint;
    price: bigint;
    videoUrl?: string;
}
export interface backendInterface {
    addCategory(name: string, description: string, imageUrl: string, videoUrl: string | null): Promise<Category>;
    addProduct(categoryId: CategoryId, name: string, description: string, price: bigint, imageUrls: Array<string>, videoUrl: string | null, available: boolean, slotIndex: bigint, discountEnabled: boolean, discountPercent: bigint): Promise<Product>;
    addReview(productId: bigint, reviewerName: string, rating: bigint, comment: string): Promise<{
        __kind__: "ok";
        ok: Review;
    } | {
        __kind__: "err";
        err: string;
    }>;
    adminLogin(password: string): Promise<boolean>;
    deleteCategory(id: CategoryId): Promise<boolean>;
    deleteProduct(id: ProductId): Promise<boolean>;
    getActiveAnnouncement(): Promise<Announcement | null>;
    getAllOrders(): Promise<Array<Order>>;
    getAllProducts(): Promise<Array<Product>>;
    getCategories(): Promise<Array<Category>>;
    getProductReviews(productId: bigint): Promise<Array<Review>>;
    getProductSlots(categoryId: CategoryId): Promise<Array<Product>>;
    getProductsByCategory(categoryId: CategoryId): Promise<Array<Product>>;
    initializeCategorySlots(categoryId: CategoryId): Promise<boolean>;
    placeOrder(req: PlaceOrderRequest): Promise<Order>;
    setAdminPassword(oldPassword: string, newPassword: string): Promise<boolean>;
    setAnnouncement(message: string, isActive: boolean): Promise<boolean>;
    toggleAnnouncement(isActive: boolean): Promise<boolean>;
    updateCategory(id: CategoryId, name: string, description: string, imageUrl: string, videoUrl: string | null): Promise<boolean>;
    updateOrderStatus(id: OrderId, status: string): Promise<boolean>;
    updateProduct(id: ProductId, categoryId: CategoryId, name: string, description: string, price: bigint, imageUrls: Array<string>, videoUrl: string | null, available: boolean, slotIndex: bigint, discountEnabled: boolean, discountPercent: bigint): Promise<boolean>;
}
import type { Announcement as _Announcement, Category as _Category, CategoryId as _CategoryId, Product as _Product, ProductId as _ProductId, Review as _Review } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async addCategory(arg0: string, arg1: string, arg2: string, arg3: string | null): Promise<Category> {
        if (this.processError) {
            try {
                const result = await this.actor.addCategory(arg0, arg1, arg2, to_candid_opt_n1(this._uploadFile, this._downloadFile, arg3));
                return from_candid_Category_n2(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addCategory(arg0, arg1, arg2, to_candid_opt_n1(this._uploadFile, this._downloadFile, arg3));
            return from_candid_Category_n2(this._uploadFile, this._downloadFile, result);
        }
    }
    async addProduct(arg0: CategoryId, arg1: string, arg2: string, arg3: bigint, arg4: Array<string>, arg5: string | null, arg6: boolean, arg7: bigint, arg8: boolean, arg9: bigint): Promise<Product> {
        if (this.processError) {
            try {
                const result = await this.actor.addProduct(arg0, arg1, arg2, arg3, arg4, to_candid_opt_n1(this._uploadFile, this._downloadFile, arg5), arg6, arg7, arg8, arg9);
                return from_candid_Product_n5(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addProduct(arg0, arg1, arg2, arg3, arg4, to_candid_opt_n1(this._uploadFile, this._downloadFile, arg5), arg6, arg7, arg8, arg9);
            return from_candid_Product_n5(this._uploadFile, this._downloadFile, result);
        }
    }
    async addReview(arg0: bigint, arg1: string, arg2: bigint, arg3: string): Promise<{
        __kind__: "ok";
        ok: Review;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.addReview(arg0, arg1, arg2, arg3);
                return from_candid_variant_n7(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addReview(arg0, arg1, arg2, arg3);
            return from_candid_variant_n7(this._uploadFile, this._downloadFile, result);
        }
    }
    async adminLogin(arg0: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.adminLogin(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminLogin(arg0);
            return result;
        }
    }
    async deleteCategory(arg0: CategoryId): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteCategory(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteCategory(arg0);
            return result;
        }
    }
    async deleteProduct(arg0: ProductId): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteProduct(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteProduct(arg0);
            return result;
        }
    }
    async getActiveAnnouncement(): Promise<Announcement | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getActiveAnnouncement();
                return from_candid_opt_n8(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getActiveAnnouncement();
            return from_candid_opt_n8(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllOrders(): Promise<Array<Order>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllOrders();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllOrders();
            return result;
        }
    }
    async getAllProducts(): Promise<Array<Product>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllProducts();
                return from_candid_vec_n9(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllProducts();
            return from_candid_vec_n9(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCategories(): Promise<Array<Category>> {
        if (this.processError) {
            try {
                const result = await this.actor.getCategories();
                return from_candid_vec_n10(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCategories();
            return from_candid_vec_n10(this._uploadFile, this._downloadFile, result);
        }
    }
    async getProductReviews(arg0: bigint): Promise<Array<Review>> {
        if (this.processError) {
            try {
                const result = await this.actor.getProductReviews(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getProductReviews(arg0);
            return result;
        }
    }
    async getProductSlots(arg0: CategoryId): Promise<Array<Product>> {
        if (this.processError) {
            try {
                const result = await this.actor.getProductSlots(arg0);
                return from_candid_vec_n9(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getProductSlots(arg0);
            return from_candid_vec_n9(this._uploadFile, this._downloadFile, result);
        }
    }
    async getProductsByCategory(arg0: CategoryId): Promise<Array<Product>> {
        if (this.processError) {
            try {
                const result = await this.actor.getProductsByCategory(arg0);
                return from_candid_vec_n9(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getProductsByCategory(arg0);
            return from_candid_vec_n9(this._uploadFile, this._downloadFile, result);
        }
    }
    async initializeCategorySlots(arg0: CategoryId): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.initializeCategorySlots(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.initializeCategorySlots(arg0);
            return result;
        }
    }
    async placeOrder(arg0: PlaceOrderRequest): Promise<Order> {
        if (this.processError) {
            try {
                const result = await this.actor.placeOrder(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.placeOrder(arg0);
            return result;
        }
    }
    async setAdminPassword(arg0: string, arg1: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.setAdminPassword(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setAdminPassword(arg0, arg1);
            return result;
        }
    }
    async setAnnouncement(arg0: string, arg1: boolean): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.setAnnouncement(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setAnnouncement(arg0, arg1);
            return result;
        }
    }
    async toggleAnnouncement(arg0: boolean): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.toggleAnnouncement(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.toggleAnnouncement(arg0);
            return result;
        }
    }
    async updateCategory(arg0: CategoryId, arg1: string, arg2: string, arg3: string, arg4: string | null): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.updateCategory(arg0, arg1, arg2, arg3, to_candid_opt_n1(this._uploadFile, this._downloadFile, arg4));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateCategory(arg0, arg1, arg2, arg3, to_candid_opt_n1(this._uploadFile, this._downloadFile, arg4));
            return result;
        }
    }
    async updateOrderStatus(arg0: OrderId, arg1: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.updateOrderStatus(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateOrderStatus(arg0, arg1);
            return result;
        }
    }
    async updateProduct(arg0: ProductId, arg1: CategoryId, arg2: string, arg3: string, arg4: bigint, arg5: Array<string>, arg6: string | null, arg7: boolean, arg8: bigint, arg9: boolean, arg10: bigint): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.updateProduct(arg0, arg1, arg2, arg3, arg4, arg5, to_candid_opt_n1(this._uploadFile, this._downloadFile, arg6), arg7, arg8, arg9, arg10);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateProduct(arg0, arg1, arg2, arg3, arg4, arg5, to_candid_opt_n1(this._uploadFile, this._downloadFile, arg6), arg7, arg8, arg9, arg10);
            return result;
        }
    }
}
function from_candid_Category_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Category): Category {
    return from_candid_record_n3(_uploadFile, _downloadFile, value);
}
function from_candid_Product_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Product): Product {
    return from_candid_record_n6(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Announcement]): Announcement | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _CategoryId;
    name: string;
    description: string;
    imageUrl: string;
    videoUrl: [] | [string];
}): {
    id: CategoryId;
    name: string;
    description: string;
    imageUrl: string;
    videoUrl?: string;
} {
    return {
        id: value.id,
        name: value.name,
        description: value.description,
        imageUrl: value.imageUrl,
        videoUrl: record_opt_to_undefined(from_candid_opt_n4(_uploadFile, _downloadFile, value.videoUrl))
    };
}
function from_candid_record_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _ProductId;
    categoryId: _CategoryId;
    imageUrls: Array<string>;
    name: string;
    description: string;
    discountPercent: bigint;
    discountEnabled: boolean;
    available: boolean;
    slotIndex: bigint;
    price: bigint;
    videoUrl: [] | [string];
}): {
    id: ProductId;
    categoryId: CategoryId;
    imageUrls: Array<string>;
    name: string;
    description: string;
    discountPercent: bigint;
    discountEnabled: boolean;
    available: boolean;
    slotIndex: bigint;
    price: bigint;
    videoUrl?: string;
} {
    return {
        id: value.id,
        categoryId: value.categoryId,
        imageUrls: value.imageUrls,
        name: value.name,
        description: value.description,
        discountPercent: value.discountPercent,
        discountEnabled: value.discountEnabled,
        available: value.available,
        slotIndex: value.slotIndex,
        price: value.price,
        videoUrl: record_opt_to_undefined(from_candid_opt_n4(_uploadFile, _downloadFile, value.videoUrl))
    };
}
function from_candid_variant_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: _Review;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: Review;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_vec_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Category>): Array<Category> {
    return value.map((x)=>from_candid_Category_n2(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Product>): Array<Product> {
    return value.map((x)=>from_candid_Product_n5(_uploadFile, _downloadFile, x));
}
function to_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: string | null): [] | [string] {
    return value === null ? candid_none() : candid_some(value);
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
